apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfk-dr
  annotations:
  argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ''
    namespace: confluent-dr
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dr
    repoURL: 'https://github.com/sotojuan2/cfk-gitops'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true