project: default
sources:
  - repoURL: 'https://packages.confluent.io/helm'
    targetRevision: 0.1193.1
    chart: confluent-for-kubernetes
    helm: 
      valueFiles:
      - $values/cfk/values.yaml
  - repoURL: 'https://github.com/sotojuan2/cfk-gitops'
    targetRevision: dr
    ref: values
destination:
  server: 'https://kubernetes.default.svc'
  namespace: confluent-dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - ServerSideApply=true




apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ''
    namespace: confluent-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://packages.confluent.io/helm'
    targetRevision: 0.1193.1
    chart: confluent-for-kubernetes
  sources:
  - repoURL: 'https://packages.confluent.io/helm'
    targetRevision: 0.1193.1
    chart: confluent-for-kubernetes
    helm: 
      valueFiles:
      - $values/cfk/values.yaml
  - repoURL: 'https://github.com/sotojuan2/cfk-gitops'
    targetRevision: dr
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true




apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator2
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  sources: []
  project: default
project: default
sources:
  - repoURL: 'https://packages.confluent.io/helm'
    targetRevision: 0.1193.1
    chart: confluent-for-kubernetes
    helm:
      valueFiles:
        - $values/cfk/values.yaml
  - repoURL: 'https://github.com/sotojuan2/cfk-gitops'
    targetRevision: dr
    ref: values
destination:
  server: 'https://kubernetes.default.svc'
  namespace: confluent-dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - ServerSideApply=true
